#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SITE_CONFIG="${SITE_CONFIG:-$PROJECT_ROOT/configs/site.env}"
OUTPUT_DIR="${OUTPUT_DIR:-$PROJECT_ROOT/configs}"

usage() {
  cat <<'EOF'
用法：
  scripts/apply_site_config.sh [--config FILE] [--output-dir DIR]

说明：
  从统一部署模板 site.env 生成现有脚本和 systemd 使用的配置文件：
    system.conf
    sync.conf
    nodes.conf
    storage-server.env
    storage-agent.env

示例：
  cp configs/site.env.example configs/site.env
  vim configs/site.env
  scripts/apply_site_config.sh --config configs/site.env --output-dir configs
  sudo scripts/apply_site_config.sh --config configs/site.env --output-dir /etc/ssms
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --config)
      SITE_CONFIG="${2:-}"
      shift 2
      ;;
    --output-dir)
      OUTPUT_DIR="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "未知参数：$1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ -z "$SITE_CONFIG" || ! -f "$SITE_CONFIG" ]]; then
  echo "缺少统一部署配置：$SITE_CONFIG" >&2
  echo "请先执行：cp configs/site.env.example configs/site.env" >&2
  exit 1
fi

if [[ -z "$OUTPUT_DIR" ]]; then
  echo "缺少输出目录" >&2
  exit 1
fi

# shellcheck source=/dev/null
source "$SITE_CONFIG"

: "${SSMS_MANAGEMENT_HOST:?请在 site.env 中设置 SSMS_MANAGEMENT_HOST}"

SSMS_MANAGEMENT_PORT="${SSMS_MANAGEMENT_PORT:-8080}"
SSMS_MANAGEMENT_URL="${SSMS_MANAGEMENT_URL:-http://${SSMS_MANAGEMENT_HOST}:${SSMS_MANAGEMENT_PORT}}"
SSMS_SERVER_ADDR="${SSMS_SERVER_ADDR:-0.0.0.0:${SSMS_MANAGEMENT_PORT}}"
SSMS_DB_PATH="${SSMS_DB_PATH:-/var/lib/ssms/server-storage.db}"
GIN_MODE="${GIN_MODE:-release}"

STORAGE_SERVER="${STORAGE_SERVER:-$SSMS_MANAGEMENT_HOST}"
STORAGE_ROOT="${STORAGE_ROOT:-/srv/samba/users}"
STORAGE_GROUP="${STORAGE_GROUP:-storageusers}"
DEFAULT_QUOTA_GB="${DEFAULT_QUOTA_GB:-10}"
MOUNT_POINT_NAME="${MOUNT_POINT_NAME:-storage}"
SMB_WORKGROUP="${SMB_WORKGROUP:-WORKGROUP}"
SMB_NETBIOS_NAME="${SMB_NETBIOS_NAME:-SSMS-STORAGE}"

STORAGE_SYNC_HOST="${STORAGE_SYNC_HOST:-$STORAGE_SERVER}"
STORAGE_SYNC_USER="${STORAGE_SYNC_USER:-}"
STORAGE_SYNC_PROJECT_DIR="${STORAGE_SYNC_PROJECT_DIR:-}"
DEFAULT_SYNC_QUOTA_GB="${DEFAULT_SYNC_QUOTA_GB:-1}"

SSMS_AGENT_NAME="${SSMS_AGENT_NAME:-NodeA}"
SSMS_AGENT_ADDRESS="${SSMS_AGENT_ADDRESS:-}"
SSMS_AGENT_DISK="${SSMS_AGENT_DISK:-/}"
SSMS_AGENT_INTERVAL="${SSMS_AGENT_INTERVAL:-30s}"
SSMS_SERVER_URL="${SSMS_SERVER_URL:-$SSMS_MANAGEMENT_URL}"

write_kv() {
  printf '%s=%q\n' "$1" "$2"
}

write_header() {
  local target="$1"
  {
    echo "# Generated from $SITE_CONFIG by scripts/apply_site_config.sh"
    echo "# Do not edit this file directly when using the unified deployment template."
    echo "# Edit site.env, then rerun apply_site_config.sh."
    echo
  } > "$target"
}

install -d -m 0755 "$OUTPUT_DIR"

SYSTEM_CONF="$OUTPUT_DIR/system.conf"
write_header "$SYSTEM_CONF"
{
  write_kv STORAGE_ROOT "$STORAGE_ROOT"
  write_kv STORAGE_GROUP "$STORAGE_GROUP"
  write_kv DEFAULT_QUOTA_GB "$DEFAULT_QUOTA_GB"
  echo
  write_kv STORAGE_SERVER "$STORAGE_SERVER"
  write_kv MOUNT_POINT_NAME "$MOUNT_POINT_NAME"
  echo
  write_kv SMB_WORKGROUP "$SMB_WORKGROUP"
  write_kv SMB_NETBIOS_NAME "$SMB_NETBIOS_NAME"
} >> "$SYSTEM_CONF"

SYNC_CONF="$OUTPUT_DIR/sync.conf"
write_header "$SYNC_CONF"
{
  write_kv STORAGE_SYNC_HOST "$STORAGE_SYNC_HOST"
  write_kv STORAGE_SYNC_USER "$STORAGE_SYNC_USER"
  write_kv STORAGE_SYNC_PROJECT_DIR "$STORAGE_SYNC_PROJECT_DIR"
  write_kv DEFAULT_SYNC_QUOTA_GB "$DEFAULT_SYNC_QUOTA_GB"
} >> "$SYNC_CONF"

SERVER_ENV="$OUTPUT_DIR/storage-server.env"
write_header "$SERVER_ENV"
{
  write_kv SSMS_SERVER_ADDR "$SSMS_SERVER_ADDR"
  write_kv SSMS_DB_PATH "$SSMS_DB_PATH"
  write_kv GIN_MODE "$GIN_MODE"
} >> "$SERVER_ENV"

AGENT_ENV="$OUTPUT_DIR/storage-agent.env"
write_header "$AGENT_ENV"
{
  write_kv SSMS_SERVER_URL "$SSMS_SERVER_URL"
  write_kv SSMS_AGENT_NAME "$SSMS_AGENT_NAME"
  write_kv SSMS_AGENT_ADDRESS "$SSMS_AGENT_ADDRESS"
  write_kv SSMS_AGENT_DISK "$SSMS_AGENT_DISK"
  write_kv SSMS_AGENT_INTERVAL "$SSMS_AGENT_INTERVAL"
} >> "$AGENT_ENV"

NODES_CONF="$OUTPUT_DIR/nodes.conf"
write_header "$NODES_CONF"
{
  echo "# 格式：节点名 主机地址 SSH用户 项目目录"
  echo
  if [[ -n "${SSMS_NODES:-}" ]]; then
    while IFS= read -r line; do
      [[ -z "${line//[[:space:]]/}" ]] && continue
      printf '%s\n' "$line"
    done <<< "$SSMS_NODES"
  else
    echo "# 未配置 SSMS_NODES。需要批量同步登录节点时，请在 site.env 中填写。"
  fi
} >> "$NODES_CONF"

cat <<EOF
已生成统一部署配置：
  $SYSTEM_CONF
  $SYNC_CONF
  $NODES_CONF
  $SERVER_ENV
  $AGENT_ENV
EOF
